Repository spring-b-hotsix/hotsix-project, pull requests merged in 2023-08, with the labels that each got.

#10 [Feat] 예외처리 - GlobalExceptionHandler
  src/main/java/com/sparta/hotsixproject/common/dto/ApiResponseDto.java
  src/main/java/com/sparta/hotsixproject/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/hotsixproject/exception/NotFoundException.java
  src/main/java/com/sparta/hotsixproject/exception/UnauthorizedException.java
Labels: exception

#12 [Feature] 첨부파일 기능 구현
  build.gradle
  src/main/java/com/sparta/hotsixproject/attachment/controller/AttachmentController.java
  src/main/java/com/sparta/hotsixproject/attachment/dto/AttachmentNameRequestDto.java
  src/main/java/com/sparta/hotsixproject/attachment/dto/AttachmentResponseDto.java
  src/main/java/com/sparta/hotsixproject/attachment/entity/Attachment.java
  src/main/java/com/sparta/hotsixproject/attachment/repository/AttachmentRepository.java
  src/main/java/com/sparta/hotsixproject/attachment/service/AttachmentService.java
  src/main/java/com/sparta/hotsixproject/card/entity/Card.java
  src/main/java/com/sparta/hotsixproject/common/config/FileConfig.java
  src/main/java/com/sparta/hotsixproject/common/file/FileUploader.java
  src/main/resources/application.properties
Labels: enhancement

#14 [Feature] 카드 상세 기능 - 댓글 기능 구현 및 예외처리
  build.gradle
  src/main/java/com/sparta/hotsixproject/HotsixProjectApplication.java
  src/main/java/com/sparta/hotsixproject/card/entity/Card.java
  src/main/java/com/sparta/hotsixproject/comment/controller/CommentController.java
  src/main/java/com/sparta/hotsixproject/comment/dto/CommentListResponseDto.java
  src/main/java/com/sparta/hotsixproject/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/hotsixproject/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/hotsixproject/comment/entity/Comment.java
  src/main/java/com/sparta/hotsixproject/comment/repository/CommentRepository.java
  src/main/java/com/sparta/hotsixproject/comment/service/CommentService.java
  src/main/java/com/sparta/hotsixproject/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/hotsixproject/common/dto/ApiResponseDto.java
  src/main/java/com/sparta/hotsixproject/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/hotsixproject/exception/annotation/CommentCheckPageAndUser.java
  src/main/java/com/sparta/hotsixproject/exception/aop/CommentCheckPageAndUserAspect.java
Labels: enhancement, exception

#18 [Feature] 카드 상세 기능 - 날짜 지정 기능 구현
  src/main/java/com/sparta/hotsixproject/card/controller/CardController.java
  src/main/java/com/sparta/hotsixproject/card/dto/CardResponseDto.java
  src/main/java/com/sparta/hotsixproject/card/dto/DueRequestDto.java
  src/main/java/com/sparta/hotsixproject/card/entity/Card.java
  src/main/java/com/sparta/hotsixproject/card/service/CardService.java
  src/main/java/com/sparta/hotsixproject/user/entity/User.java
Labels: bug, enhancement

#22 [Feature] 카드 추가 기능 - 체크리스트 기능 구현 및 예외처리
  src/main/java/com/sparta/hotsixproject/board/service/BoardServiceImpl.java
  src/main/java/com/sparta/hotsixproject/checklist/checklistItem/dto/ChecklistItemRequestDto.java
  src/main/java/com/sparta/hotsixproject/checklist/checklistItem/dto/ChecklistItemResponseDto.java
  src/main/java/com/sparta/hotsixproject/checklist/checklistItem/entity/ChecklistItem.java
  src/main/java/com/sparta/hotsixproject/checklist/checklistItem/repository/ChecklistItemRepository.java
  src/main/java/com/sparta/hotsixproject/checklist/controller/ChecklistController.java
  src/main/java/com/sparta/hotsixproject/checklist/dto/ChecklistRequestDto.java
  src/main/java/com/sparta/hotsixproject/checklist/dto/ChecklistResponseDto.java
  src/main/java/com/sparta/hotsixproject/checklist/dto/ChecklistsResponseDto.java
  src/main/java/com/sparta/hotsixproject/checklist/entity/Checklist.java
  src/main/java/com/sparta/hotsixproject/checklist/repository/ChecklistRepository.java
  src/main/java/com/sparta/hotsixproject/checklist/service/ChecklistService.java
  src/main/java/com/sparta/hotsixproject/checklist/service/ChecklistServiceImpl.java
  src/main/java/com/sparta/hotsixproject/exception/annotation/ChecklistCheckPageAndUser.java
  src/main/java/com/sparta/hotsixproject/exception/annotation/ChecklistItemCheckPageAndUser.java
  src/main/java/com/sparta/hotsixproject/exception/aop/ChecklistCheckPageAndUserAspect.java
Labels: enhancement, exception

#25 [Feature] 컬럼 관리 기능
  build.gradle
  src/main/java/com/sparta/hotsixproject/board/entity/Board.java
  src/main/java/com/sparta/hotsixproject/card/service/CardService.java
  src/main/java/com/sparta/hotsixproject/common/config/QueryDslConfiguration.java
  src/main/java/com/sparta/hotsixproject/side/controller/SideController.java
  src/main/java/com/sparta/hotsixproject/side/dto/SideMoveDto.java
  src/main/java/com/sparta/hotsixproject/side/dto/SideRequestDto.java
  src/main/java/com/sparta/hotsixproject/side/dto/SideResponseDto.java
  src/main/java/com/sparta/hotsixproject/side/entity/Side.java
  src/main/java/com/sparta/hotsixproject/side/repository/SideRepository.java
  src/main/java/com/sparta/hotsixproject/side/repository/SideRepositoryCustom.java
  src/main/java/com/sparta/hotsixproject/side/repository/SideRepositoryImpl.java
  src/main/java/com/sparta/hotsixproject/side/service/Impl/SideCustomServiceImpl.java
  src/main/java/com/sparta/hotsixproject/side/service/SideCustomService.java
Labels: enhancement

#29 [Feature] 카드에 작업자 추가
  src/main/java/com/sparta/hotsixproject/board/controller/BoardController.java
  src/main/java/com/sparta/hotsixproject/board/dto/MemberResponseDto.java
  src/main/java/com/sparta/hotsixproject/board/repository/BoardUserRepository.java
  src/main/java/com/sparta/hotsixproject/board/service/BoardService.java
  src/main/java/com/sparta/hotsixproject/board/service/BoardServiceImpl.java
  src/main/java/com/sparta/hotsixproject/card/controller/CardController.java
  src/main/java/com/sparta/hotsixproject/card/dto/CardResponseDto.java
  src/main/java/com/sparta/hotsixproject/card/dto/InviteCardRequestDto.java
  src/main/java/com/sparta/hotsixproject/card/entity/Card.java
  src/main/java/com/sparta/hotsixproject/card/repository/CardRepository.java
  src/main/java/com/sparta/hotsixproject/card/service/CardService.java
  src/main/java/com/sparta/hotsixproject/carduser/entity/CardUser.java
  src/main/java/com/sparta/hotsixproject/carduser/repository/CardUserRepository.java
  src/main/java/com/sparta/hotsixproject/user/dto/UserInfoResponseDto.java
  src/main/java/com/sparta/hotsixproject/user/entity/User.java
  src/main/java/com/sparta/hotsixproject/user/service/UserService.java
  src/main/resources/application.properties
Labels: enhancement

#31 [Update] ResponseDto 수정
  src/main/java/com/sparta/hotsixproject/attachment/dto/AttachmentResponseDto.java
  src/main/java/com/sparta/hotsixproject/board/dto/BoardResponseDto.java
  src/main/java/com/sparta/hotsixproject/card/dto/CardResponseDto.java
  src/main/java/com/sparta/hotsixproject/card/entity/Card.java
  src/main/java/com/sparta/hotsixproject/checklist/checklistItem/entity/ChecklistItem.java
  src/main/java/com/sparta/hotsixproject/checklist/entity/Checklist.java
  src/main/java/com/sparta/hotsixproject/comment/CommentStatus.java
  src/main/java/com/sparta/hotsixproject/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/hotsixproject/comment/entity/Comment.java
  src/main/java/com/sparta/hotsixproject/comment/service/CommentServiceImpl.java
  src/main/java/com/sparta/hotsixproject/label/dto/LabelResponseDto.java
  src/main/java/com/sparta/hotsixproject/side/dto/SideResponseDto.java
Labels: refactor

#39 [Feature] Swagger 추가
  src/main/java/com/sparta/hotsixproject/attachment/controller/AttachmentController.java
  src/main/java/com/sparta/hotsixproject/board/controller/BoardController.java
  src/main/java/com/sparta/hotsixproject/card/controller/CardController.java
  src/main/java/com/sparta/hotsixproject/comment/controller/CommentController.java
  src/main/java/com/sparta/hotsixproject/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/hotsixproject/label/controller/LabelController.java
  src/main/java/com/sparta/hotsixproject/side/controller/SideController.java
  src/main/java/com/sparta/hotsixproject/user/controller/UserController.java
Labels: documentation, enhancement

#40 [Refactor] 카드 추가 기능 - 라벨 기능 리팩토링 및 예외 처리
  src/main/java/com/sparta/hotsixproject/board/entity/Board.java
  src/main/java/com/sparta/hotsixproject/card/entity/Card.java
  src/main/java/com/sparta/hotsixproject/cardlabel/entity/CardLabel.java
  src/main/java/com/sparta/hotsixproject/cardlabel/repository/CardLabelRepository.java
  src/main/java/com/sparta/hotsixproject/exception/annotation/LabelCheckPageAndUser.java
  src/main/java/com/sparta/hotsixproject/exception/aop/ChecklistCheckPageAndUserAspect.java
  src/main/java/com/sparta/hotsixproject/exception/aop/CommentCheckPageAndUserAspect.java
  src/main/java/com/sparta/hotsixproject/exception/aop/CommonPageAndUserCheckAspect.java
  src/main/java/com/sparta/hotsixproject/exception/aop/LabelCheckPageAndUserAspect.java
  src/main/java/com/sparta/hotsixproject/label/controller/LabelController.java
  src/main/java/com/sparta/hotsixproject/label/dto/LabelResponseDto.java
  src/main/java/com/sparta/hotsixproject/label/entity/Label.java
  src/main/java/com/sparta/hotsixproject/label/repository/LabelRepository.java
  src/main/java/com/sparta/hotsixproject/label/service/LabelService.java
Labels: exception, refactor

#34 [Feature] 소셜로그인 기능 추가
  src/main/java/com/sparta/hotsixproject/common/config/RestTemplateConfig.java
  src/main/java/com/sparta/hotsixproject/user/controller/UserController.java
  src/main/java/com/sparta/hotsixproject/user/dto/GoogleUserInfoDto.java
  src/main/java/com/sparta/hotsixproject/user/dto/KakaoUserInfoDto.java
  src/main/java/com/sparta/hotsixproject/user/entity/User.java
  src/main/java/com/sparta/hotsixproject/user/repository/UserRepository.java
  src/main/java/com/sparta/hotsixproject/user/service/GoolgeService.java
  src/main/java/com/sparta/hotsixproject/user/service/KakaoService.java
  src/main/java/com/sparta/hotsixproject/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/css/style.css
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: enhancement

#44 [Fix] 카카오 소셜로그인 버그 수정
  src/main/java/com/sparta/hotsixproject/user/controller/UserController.java
  src/main/java/com/sparta/hotsixproject/user/entity/User.java
  src/main/java/com/sparta/hotsixproject/user/service/KakaoService.java
Labels: bug

#53 [Feature] 보드 및 카드 정적 페이지 작성
  src/main/resources/templates/board.html
  src/main/resources/templates/card.html
Labels: enhancement, front

#55 [Fix] 보드 정적 페이지 수정
  src/main/resources/templates/board.html
Labels: bug, front

#56 [Feature] 개인 프로필 페이지 생성
  src/main/java/com/sparta/hotsixproject/user/controller/UserController.java
  src/main/resources/static/js/cookie.min.js
  src/main/resources/templates/index.html
  src/main/resources/templates/profile.html
Labels: enhancement

#57 [Feature] 카드 알람 기능 구현
  src/main/generated/com/sparta/hotsixproject/user/entity/QUser.java
  src/main/java/com/sparta/hotsixproject/card/controller/CardController.java
  src/main/java/com/sparta/hotsixproject/card/event/CardUpdateEvent.java
  src/main/java/com/sparta/hotsixproject/card/event/CardUpdateEventListener.java
  src/main/java/com/sparta/hotsixproject/card/event/EventPublisher.java
  src/main/java/com/sparta/hotsixproject/card/repository/CardRepository.java
  src/main/java/com/sparta/hotsixproject/card/service/CardService.java
  src/main/java/com/sparta/hotsixproject/notification/NotificationTitle.java
  src/main/java/com/sparta/hotsixproject/notification/controller/NotificationController.java
  src/main/java/com/sparta/hotsixproject/notification/dto/NotificationResponseDto.java
  src/main/java/com/sparta/hotsixproject/notification/entity/Notification.java
  src/main/java/com/sparta/hotsixproject/notification/repository/NotificationRepository.java
  src/main/java/com/sparta/hotsixproject/notification/service/NotificationService.java
  src/main/java/com/sparta/hotsixproject/user/entity/User.java
Labels: enhancement

#60 [Feature] 키워드로 카드 검색 기능 추가
  src/main/java/com/sparta/hotsixproject/board/controller/BoardController.java
  src/main/java/com/sparta/hotsixproject/board/service/BoardService.java
  src/main/java/com/sparta/hotsixproject/board/service/BoardServiceImpl.java
  src/main/java/com/sparta/hotsixproject/card/repository/CardRepository.java
Labels: enhancement

#64 [Feature] 프로필 사진 업데이트 기능 추가
  src/main/generated/com/sparta/hotsixproject/user/entity/QUser.java
  src/main/java/com/sparta/hotsixproject/card/dto/CardResponseDto.java
  src/main/java/com/sparta/hotsixproject/user/controller/UserController.java
  src/main/java/com/sparta/hotsixproject/user/dto/UserInfoDto.java
  src/main/java/com/sparta/hotsixproject/user/dto/UserInfoResponseDto.java
  src/main/java/com/sparta/hotsixproject/user/entity/User.java
  src/main/java/com/sparta/hotsixproject/user/service/UserService.java
Labels: enhancement

#69 [Fix] 테스트 코드에 적용할 DB 및 변경 사항 추가
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  src/main/java/com/sparta/hotsixproject/user/dto/LoginRequestDto.java
  src/main/java/com/sparta/hotsixproject/user/entity/User.java
  src/test/java/com/sparta/hotsixproject/HotsixProjectApplicationTests.java
Labels: documentation, refactor, information sharing

#70 [Test] 테스트 코드 확인을 위한 PR_v4
  .github/workflows/gradle.yml
  src/main/java/com/sparta/hotsixproject/user/dto/LoginRequestDto.java
  src/main/java/com/sparta/hotsixproject/user/entity/User.java
  src/test/java/com/sparta/hotsixproject/user/service/UserServiceTest.java
Labels: information sharing, test

#81 [Refactor] 알람 비동기 처리로 로직 다시 수정
  src/main/java/com/sparta/hotsixproject/card/event/CardUpdateEventListener.java
  src/main/java/com/sparta/hotsixproject/card/event/EventPublisher.java
Labels: refactor

#75 [Fix] 컬럼 이동 후 컬럼 생성 시 position 문제 수정
  src/main/java/com/sparta/hotsixproject/side/service/Impl/SideCustomServiceImpl.java
Labels: bug

#80 [Feature] 더미 데이터 생성
  build.gradle
  src/main/java/com/sparta/hotsixproject/checklist/checklistItem/dto/ChecklistItemRequestDto.java
  src/main/java/com/sparta/hotsixproject/checklist/dto/ChecklistRequestDto.java
  src/main/java/com/sparta/hotsixproject/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/hotsixproject/common/dummy/DummyGenerator.java
Labels: enhancement

#87 [Refactor] 소셜 로그인 url 수정
  appspec.yml
  src/main/java/com/sparta/hotsixproject/user/service/GoolgeService.java
  src/main/java/com/sparta/hotsixproject/user/service/KakaoService.java
  src/main/resources/templates/login.html
Labels: refactor

#88 [Test] CD 테스트 용 PR
  .github/workflows/deploy.yml
  .github/workflows/gradle.yml
  appspec.yml
Labels: documentation

#102 [Feature] 유저 프로필 프론트엔드 추가
  src/main/java/com/sparta/hotsixproject/user/controller/UserController.java
  src/main/java/com/sparta/hotsixproject/user/dto/UserInfoDto.java
  src/main/java/com/sparta/hotsixproject/user/service/UserService.java
  src/main/resources/templates/profile.html
Labels: enhancement
